//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoder.PmvAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demoder.PmvAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;&lt;root&gt;
        ///  &lt;Playfield id=&quot;505&quot; name=&quot;Avalon&quot; x=&quot;35214&quot; xscale=&quot;1.00000&quot; z=&quot;44566&quot; zscale=&quot;1.00000&quot;/&gt;
        ///  &lt;Playfield id=&quot;540&quot; name=&quot;Old Athen&quot; x=&quot;39621&quot; xscale=&quot;1.00000&quot; z=&quot;40670&quot; zscale=&quot;1.00000&quot;/&gt;
        ///  &lt;Playfield id=&quot;545&quot; name=&quot;West Athen&quot; x=&quot;39122&quot; xscale=&quot;1.00000&quot; z=&quot;40646&quot; zscale=&quot;1.00000&quot;/&gt;
        ///  &lt;Playfield id=&quot;550&quot; name=&quot;Athen Shire&quot; x=&quot;37085&quot; xscale=&quot;1.00000&quot; z=&quot;39823&quot; zscale=&quot;1.00000&quot;/&gt;
        ///  &lt;Playfield id=&quot;551&quot; name=&quot;Wailing Wastes&quot; x=&quot;37078&quot; xscale=&quot;1.00000&quot; z=&quot;41004&quot; zscale=&quot;1.00000&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapCoordinates {
            get {
                return ResourceManager.GetString("MapCoordinates", resourceCulture);
            }
        }
    }
}
