//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoder.PlanetMapViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GuiFonts : global::System.Configuration.ApplicationSettingsBase {
        
        private static GuiFonts defaultInstance = ((GuiFonts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GuiFonts())));
        
        public static GuiFonts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CourierNew8")]
        public global::Demoder.PlanetMapViewer.LoadedFont Small {
            get {
                return ((global::Demoder.PlanetMapViewer.LoadedFont)(this["Small"]));
            }
            set {
                this["Small"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CourierNew10")]
        public global::Demoder.PlanetMapViewer.LoadedFont Normal {
            get {
                return ((global::Demoder.PlanetMapViewer.LoadedFont)(this["Normal"]));
            }
            set {
                this["Normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CourierNew12")]
        public global::Demoder.PlanetMapViewer.LoadedFont Large {
            get {
                return ((global::Demoder.PlanetMapViewer.LoadedFont)(this["Large"]));
            }
            set {
                this["Large"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CourierNew18")]
        public global::Demoder.PlanetMapViewer.LoadedFont XLarge {
            get {
                return ((global::Demoder.PlanetMapViewer.LoadedFont)(this["XLarge"]));
            }
            set {
                this["XLarge"] = value;
            }
        }
    }
}
