//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoder.PlanetMapViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MapFonts : global::System.Configuration.ApplicationSettingsBase {
        
        private static MapFonts defaultInstance = ((MapFonts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MapFonts())));
        
        public static MapFonts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SilkScreen7")]
        public global::Demoder.PlanetMapViewer.LoadedFont CharLocator {
            get {
                return ((global::Demoder.PlanetMapViewer.LoadedFont)(this["CharLocator"]));
            }
            set {
                this["CharLocator"] = value;
            }
        }
    }
}
