//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoder.PlanetMapViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class OverlayTutorial : global::System.Configuration.ApplicationSettingsBase {
        
        private static OverlayTutorial defaultInstance = ((OverlayTutorial)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OverlayTutorial())));
        
        public static OverlayTutorial Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TitlebarMenu {
            get {
                return ((bool)(this["TitlebarMenu"]));
            }
            set {
                this["TitlebarMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResizeWindow {
            get {
                return ((bool)(this["ResizeWindow"]));
            }
            set {
                this["ResizeWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExitOverlayMode {
            get {
                return ((bool)(this["ExitOverlayMode"]));
            }
            set {
                this["ExitOverlayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TitlebarMenuClosed {
            get {
                return ((bool)(this["TitlebarMenuClosed"]));
            }
            set {
                this["TitlebarMenuClosed"] = value;
            }
        }
    }
}
